local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: "S3"
  access_key_id: "AKIA25AMRR5KS3VLSXCW"
  secret_access_key: "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"
  bucket: "main-prepdd"
  region: "us-east-1"
